{{- if not .Values.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app-runner.fullname" . }}
  labels:
    {{- include "java-app-runner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: app-port
    protocol: {{ .Values.service.protocol }}
    name: app-port
  {{- if and .Values.health .Values.health.enabled }}
  - port: {{ .Values.health.port }}
    targetPort: health
    protocol: TCP
    name: health
  {{- end }}
  selector:
    {{- include "java-app-runner.selectorLabels" . | nindent 4 }}
{{- end }}

